### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by gbertb** [MagnivOrg/promptlayer-js-helper#1]
Do you know if there's a way to setup promptlayer in streaming mode in openai?

**Comment by Jped** [comment]
If you are using javascript, the best way you can do it right now is to use the standard openai streaming feature, keep track of all the responses and when the stream finishes send the full response back to promptlayer.

That is how we do it in python. Does that make sense?

**Comment by gbertb** [comment]
Yep that makes sense. I figured it was along the same lines.

**Comment by mso1830** [comment]
Did you figure it out @gbertb ?
it's a bit confusing to me.

**Comment by Jped** [comment]
@mso1830 Take a [look here](https://github.com/MagnivOrg/prompt-layer-library/blob/09feb32ee13cbbf89ab440b989372e5357f47294/promptlayer/utils.py#L308) in our python library -- if you can follow through the logic it should make sense.

Basically we have a results dictionary that we hold on to and then once we get to an end reason we send that to our api
